### PR TITLE
add some labs

### PR DESCRIPTION
**Pull request by sachiniyer**
I wrote up a list of labs for something else, and thought it could be useful here.

If this is not useful, or clean enough, please close. :smile:

### CODE REVIEW

**Comment by aminoa** [comment]
This is great collection of labs! I'm currently reformatting it to give more context to each of the labs; also I removed the non-NYU affiliated labs for now since adding another page may be a better fit. Ditto for the professor pages.

**Comment by aminoa** [comment]
I added the information but there is a bit too much information on the page right now; I tried cutting resources but it still needs to be trimmed more. Maybe a selected list of labs (and having other labs on another page)? I think some of the labs are not very currently. 

This is the stuff I ended up cutting from the page. 
  
 
 
 
  - [ALT Steering Committee | AALT](http://algorithmiclearningtheory.org/alt-steering-committee/)
Resources:
 
  - [AIIRA :: Home](https://aiira.iastate.edu/)
[ALSDC Group – Atomic-Level Structural Dynamics in Catalysts](https://alsdcgroup.wordpress.com/):  
  - [M²LInES](https://m2lines.github.io/)


 - [Mehryar Mohri -- Foundations of Machine Learning - Book](https://cs.nyu.edu/~mohri/mlbook/)
  
   - [Group :: Joan Bruna](https://cims.nyu.edu/~bruna/group/)
   
   Professors:

 - [Brian McFee](https://brianmcfee.net/): I develop machine learning tools to analyze music and multimedia data. This includes recommender systems, image and audio analysis, similarity learning, cross-modal feature integration, and automatic annotation.

 - [Benjamin Peherstorfer - Group](https://cims.nyu.edu/~pehersto/group.html): My research interests are broadly in computational mathematics for scientific computing and machine learning. All research topics are multidisciplinary in the sense that they intersect with various aspects of mathematics of data science, computational statistics, numerical analysis, and computer science.

 - [Sonali Shukla McDermid](http://www.sonalimcdermid.com/)
 
  - [Chunara Lab – Computer Science & Engineering And Global Public Health](https://wp.nyu.edu/chunaralab/)
   - [Home Page of Mohamed M. Zahran](http://www.mzahran.com/index.html)
   
   -  - [Aurojit Panda](https://cs.nyu.edu/~apanda/)
   
 - [Qi Lei (雷琦)](https://cecilialeiqi.github.io/)
 
  - [Group - Chinmay Hegde](https://chinmayhegde.github.io/lab/)
  
   - [Learning Science Lab - NYU Stern](https://www.stern.nyu.edu/portal-partners/faculty-staff/learning-science-lab) (don't think this actually does research)
   
    - [flinkerlab – Speech Language Electrocorticography](https://flinkerlab.org/)  (don't think cs related)
	
	 - [Ivan Selesnick](https://eeweb.engineering.nyu.edu/iselesni/)
 - [JohnRoss Rizzo](https://med.nyu.edu/faculty/johnross-rizzo)
 
  - [Home | Hudson Lab](https://www.hudsonlab.org/)
 - [Guido Gerig's homepage](http://engineering.nyu.edu/~gerig/)

**Comment by sachiniyer** [comment]
Okay I will put in some more work this weekend. Is there something that you are looking for while cutting?

One example of a lab that I thought was useful was the Bruna group.

**Comment by aminoa** [comment]
I think just keeping it focused on labs at NYU and avoiding labs which haven't had activity for the last year would be good. I cut Bruna since I thought it would make more sense to put him on a professors page instead but I don't have a strong preference for him being on the labs page too.

**Comment by sachiniyer** [comment]
Okay, that makes sense. I think a lot of professors also hold their lab pages on their personal page. But not sure how to deal with that grey area.

**Comment by aminoa** [comment]
I think it's fine if we lean towards keeping them on this page if there's a grey area.

**Comment by sachiniyer** [comment]
I am curious about the vision for a professor's page that would be different than the professor lists that exist on department websites. It seems that listing all professors, and maintaining an updated list would require significant maintenance.

**Comment by aminoa** [comment]
That's a fair point, it may be too much of a hassle to maintain a professors list. Ignoring that, I'll merge the changes; thanks for the contribution!

**Pull request merged**
