### PR TITLE
ADD free stuff

### PR DESCRIPTION
**Pull request by calvinatian**
#9 #24

Potentially add a discount section for stuff that is not free

### CODE REVIEW

**Comment by sachiniyer** [comment]
Maybe a few things worth adding:
 - HPC access
 - NYU GCP - https://www.nyu.edu/life/information-technology/communication-and-collaboration/email-and-communication/google-services/nyu-google-services.html (I got an instance for the sem during eg1003 through this, not sure if it still applies)
 - eLab - https://entrepreneur.nyu.edu/resource/leslie-elab/
 - prototyping fund - https://www.startpage.com/do/dsearch?query=nyu+makerspace+fund&cat=web&pl=ext-ff&language=english&extVersion=1.3.0

**Comment by aminoa** [comment]
Some more things: 

- Box provides free cloud storage for NYU accounts (https://www.nyu.edu/life/information-technology/communication-and-collaboration/document-collaboration-and-sharing/nyu-box.html)
- For residential students (in a dorm), free HBO max (https://www.nyu.edu/students/student-information-and-resources/housing-and-dining/on-campus-living/residence-halls/campus-cable/hbo-max.html)
- Via/Safe Ride (free transportation between dorms after 11:00 PM and before 7:00 AM) (https://www.nyu.edu/life/travel-and-transportation/university-transportation/safe-ride-van-service.html)

**Comment by calvinatian** [comment]
> Maybe a few things worth adding:
> 
>     * HPC access - https://www.nyu.edu/life/information-technology/research-computing-services/high-performance-computing.html
> 
>     * NYU GCP - https://www.nyu.edu/life/information-technology/communication-and-collaboration/email-and-communication/google-services/nyu-google-services.html (I got an instance for the sem during eg1003 through this, not sure if it still applies)
> 
>     * eLab - https://entrepreneur.nyu.edu/resource/leslie-elab/
> 
>     * prototyping fund - http://makerspace.engineering.nyu.edu/funding/prototypingfund/

Added HPC anad eLab. Didn't add GCP as I couldn't sign in with my NYU account at https://cloud.google.com/

> Some more things:
> 
>     * Box provides free cloud storage for NYU accounts (https://www.nyu.edu/life/information-technology/communication-and-collaboration/document-collaboration-and-sharing/nyu-box.html)
> 
>     * For residential students (in a dorm), free HBO max (https://www.nyu.edu/students/student-information-and-resources/housing-and-dining/on-campus-living/residence-halls/campus-cable/hbo-max.html)
> 
>     * Via/Safe Ride (free transportation between dorms after 11:00 PM and before 7:00 AM) (https://www.nyu.edu/life/travel-and-transportation/university-transportation/safe-ride-van-service.html)

Added Max and Safe Ride. Box seems to be restricted to faculty so I skipped it.

I think it's good to merge for now. In the future we could rethink the layout as it's just an alphabetical list for now. Maybe we could highlight certain perks or have a better way of displaying the information.

**Comment by sachiniyer** [comment]
btw, [here](https://sites.google.com/nyu.edu/nyu-hpc/hpc-systems/cloud-computing/gcp-self-managed-projects) is an article about GCP.

I would not consider this requisite to merging though. Can always be added later.

**Review by aminoa — APPROVED** [review]

**Pull request merged**
