### PR TITLE
add some profs

### PR DESCRIPTION
**Pull request by sachiniyer**
Add profs (388 of them?)

### CODE REVIEW

**Comment by aminoa** [comment]
extracted names from all page links via chatgpt calls, will probably split out into separate pages since this file will get too long with just 1 file.

**Comment by sachiniyer** [comment]
I am curious on how the filtering works. Why doesn't someone like https://jwbaek.github.io/ get added?

**Comment by aminoa** [comment]
ah that was a mistake; I was focusing on either labs which didn't directly link to a professor (ex. the high speed research lab https://research.engineering.nyu.edu/highspeed/) or links which were simply broken. I'll check over again to verify I don't remove any proper professor pages.

**Comment by sachiniyer** [comment]
hmm, I would take the approach of not have a very light filter. Many professor's primary page is their lab page (where they are the PI). (e.g. for https://research.engineering.nyu.edu/highspeed - that is Jonathan Chao's mainpage).

I also think all those links worked? At least on my machine.

**Comment by aminoa** [comment]
Finally got the chance to review through all the professors again; for transparency, I included the moved/removed links below:

Moved (put in the labs section): 
http://www.mp3l.org/

Removed:
https://research.engineering.nyu.edu/highspeed
https://www.immersivecomputinglab.org/
https://www.geosimulation.org/bio.html

For the removed pieces, I added a direct link to the professor page in lieu so you should still be able to get back to the lab page. I didn't want to link lab pages directly since they don't really fit with the professor page area. In terms of adding them to the labs page, I wasn't sure about whether to add the high speed page. I'm skipping the geosimulation page for now (but may go back to add it later). 

Also, since this PR is quite large, it may be worth splitting the research summary generation part into a later PR; what are your thoughts?

**Comment by sachiniyer** [comment]
Sorry for the late response...working life takes time.

I wrote a script to find your changes. If I felt no change was necessary, then I added the prof back. Otherwise, I changed the link to their profile.
```
https://daniel-zint.github.io/
https://cs.nyu.edu/~tr51/
https://musedlab.org/ for https://steinhardt.nyu.edu/people/s-alex-ruthmann
https://research.engineering.nyu.edu/highspeed/ for https://engineering.nyu.edu/faculty/yang-xu
https://sites.google.com/nyu.edu/zamlab?pli=1 for https://sites.google.com/nyu.edu/zamlab/azharzam?authuser=0
https://www.immersivecomputinglab.org/ for https://engineering.nyu.edu/faculty/qi-sun
http://www.geosimulation.org/bio.html for https://engineering.nyu.edu/faculty/paul-torrens
```
Hopefully we have fixed everything.

I completely agree. Research Summary Generation should be done sometime else. This has imo enough value to be merged right now.

**Review by aminoa — APPROVED** [review]
LGTM!

**Pull request merged**
