### PR TITLE
Algolia fix, VIP info add

### LINKED ISSUE #54: FAMS VIP
You know, I heard this VIP before so I'd appreciate it if an article was made ;)

### PR DESCRIPTION
**Pull request by aminoa**
Merging Thaison's changes

### CODE REVIEW

**Review by nedjulius — APPROVED** [review]

**Comment by nedjulius** [comment]
what is this file `docusaurus.config.js.swp`?

**Review by nedjulius — CHANGES_REQUESTED** [review]
what is this file `docusaurus.config.js.swp`? should we add this file format to `.gitignore`?

**Comment by aminoa** [comment]
hmm not actually sure

**Comment by nedjulius** [comment]
@aminoa can you commit the changes?

**Comment by aminoa** [comment]
done

**Pull request merged**
